apiVersion: v1
kind: ReplicationController
metadata:
  name: rcsise
spec:
  replicas: 5
  selector:
    app: sise
  template:
    metadata:
      name: somebadpods
      labels:
        app: sise
    spec:
      containers:
      - name: sise
        image: mhausenblas/simpleservice:0.5.0
        ports:
        - containerPort: 9876
        env:
        - name: HEALTH_MAX
          value: "3100"
        readinessProbe:
          initialDelaySeconds: 3
          httpGet:
            path: /health
            port: 9876
