apiVersion: apps/v1 #  Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:   #permite seleccionar un conjunto de objetos que cumplan las condicione
    matchLabels:
      app: helloworld
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
