apiVersion: v1
kind: Pod
metadata:
  name: my-nfs-pod
  labels:
    app: helloworld
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: nfs-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nfs-volume
      nfs:
        server: 10.0.0.10
        path: /bd-nfs
